#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/modules/web3/ethereum_provider.js"
OUT_DIR="$ROOT/modules/web3/generated"
OUT_JS="$OUT_DIR/ethereum_provider.min.js"
OUT_CC="$OUT_DIR/ethereum_provider_generated.h"
mkdir -p "$OUT_DIR"
[[ -f "$SRC" ]] || { echo "Source not found: $SRC"; exit 1; }
echo "==> Preparing Web3 provider for Chromium injection"
python3 - "$SRC" "$OUT_JS" <<'PY'
import sys, re
src, dst = sys.argv[1], sys.argv[2]
code = open(src, encoding='utf-8').read()
code = re.sub(r'/\*.*?\*/', '', code, flags=re.DOTALL)
code = re.sub(r'//.*?$', '', code, flags=re.MULTILINE)
code = re.sub(r'[ \t]+', ' ', code)
code = re.sub(r'\n\s*\n', '\n', code).strip()
open(dst, 'w', encoding='utf-8').write(code)
print(f'Wrote {dst} ({len(code)} bytes)')
PY
python3 - "$OUT_JS" "$OUT_CC" <<'PY'
import sys
src, dst = sys.argv[1], sys.argv[2]
code = open(src, encoding='utf-8').read()
if ')JS"' in code:
    code = code.replace(')JS"', ')JS \"')
header = f'''// AUTO-GENERATED by prepare_web3_injection.sh\n#ifndef WEB3_ETHEREUM_PROVIDER_GENERATED_H_\n#define WEB3_ETHEREUM_PROVIDER_GENERATED_H_\nnamespace web3_browser {{\nconstexpr char kEthereumProviderScript[] = R"JS(\n{code}\n)JS";\n}}\n#endif\n'''
open(dst, 'w', encoding='utf-8').write(header)
print(f'Wrote {dst}')
PY
echo "==> Done"
